### ISSUE TITLE
Drag and drop function deletes the file!

### ISSUE THREAD

**Issue by ThePip** [ModPlugPlayer/ModPlugPlayer#1]
Drag and drop function deletes the file! At least by my testing on all the windows versions of this, and on windows 10.
fortunately I didnt lose a file I cant get back, but you have been warned!

**Comment by volkanorhan** [comment]
This problem was fixed on Alpha 3 version. I am adding Alpha 3 version to GitHub, too. You can access Alpha 3 version on http://www.modplugplayer.org

**Comment by volkanorhan** [comment]
This problem was fixed on Alpha 3 version. I am adding Alpha 3 version to GitHub, too. You can access Alpha 3 version on http://www.modplugplayer.org/

**Comment by volkanorhan** [comment]
Can you please remove the annoying readme message of your fork? This project is currently in alpha stage, and until beta version, there may be such bugs.
